<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <PackAsTool>true</PackAsTool>
        <ToolCommandName>tune-review</ToolCommandName>
        <PackageId>CloudAwesome.FolkTune.Reviewer</PackageId>
        
        <OutputType>Exe</OutputType>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <None Include="nuget-readme.md" Pack="true" PackagePath="\" />
    </ItemGroup>
    
    <ItemGroup>
      <PackageReference Include="Spectre.Console.Cli" Version="0.53.1" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\CloudAwesome.FolkTune\CloudAwesome.FolkTune.csproj" />
    </ItemGroup>

</Project>
